name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Lint YAML
      uses: docker://python:latest
      run: |
        pip install yamllint
        make lint-yaml

    - name: Generate Files
      uses: docker://golang:latest
      run: make gen

    - name: Format Files
      uses: docker://node:latest
      run: make fmt-yaml fmt-markdown

    - name: Publish Repo
      runs-on: ubuntu-latest
      run: |
        GITHUB_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
            git add README.md awesome-streamers.json
            git commit -m "Published $(shell date)"
            git push "${GITHUB_URL}" master:master
        fi
